# permissions for end users to view kservestacks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: kservestack-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kserve-installer
    app.kubernetes.io/part-of: kserve-installer
    app.kubernetes.io/managed-by: kustomize
  name: kservestack-viewer-role
rules:
- apiGroups:
  - kserve.kserve.example.com
  resources:
  - kservestacks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kserve.kserve.example.com
  resources:
  - kservestacks/status
  verbs:
  - get
