# permissions for end users to edit kservestacks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: kservestack-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kserve-installer
    app.kubernetes.io/part-of: kserve-installer
    app.kubernetes.io/managed-by: kustomize
  name: kservestack-editor-role
rules:
- apiGroups:
  - kserve.kserve.example.com
  resources:
  - kservestacks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kserve.kserve.example.com
  resources:
  - kservestacks/status
  verbs:
  - get
